In [14]:
import json
import gpflow
import numpy as np
import matplotlib.pyplot as plt
import math
%matplotlib inline
import seaborn as sns
sns.set_style("white")
sns.set_context("paper")
import sys
sys.path.append('../')
from Misc import syn_data_gen, save_load_files

# Load Actions Data of all occupants

In [15]:
num_data = 20

In [16]:
all_actions_data_list = []
for i in xrange(21):
    occ_num = i + 1
    print "Occupant number:"
    print occ_num
    config_file = '../data/config_files/syn/diff_utilities_config/syn_occupants.json'
    with open(config_file, 'r') as fd:
        config = json.loads(fd.read())

    a = config['O' + str(occ_num)]['a']
    b = config['O' + str(occ_num)]['b']
    
    # Load actions data
    actions_data = np.loadtxt('../data/syn_data/syn_occ/actions_data/train/' +
                         'O_a' + str(a) + '_b' + str(b) + '_' + str(num_data) + '_.csv', delimiter = ',')
    
    all_actions_data_list.append(actions_data)

Occupant number:
1
Occupant number:
2
Occupant number:
3
Occupant number:
4
Occupant number:
5
Occupant number:
6
Occupant number:
7
Occupant number:
8
Occupant number:
9
Occupant number:
10
Occupant number:
11
Occupant number:
12
Occupant number:
13
Occupant number:
14
Occupant number:
15
Occupant number:
16
Occupant number:
17
Occupant number:
18
Occupant number:
19
Occupant number:
20
Occupant number:
21


In [17]:
all_actions_data_list[8]

array([[ 0.67346939,  0.7755102 ],
       [ 0.04081633,  0.42857143],
       [ 0.89795918,  0.93877551],
       [ 0.18367347,  0.97959184],
       [ 0.24489796,  0.48979592],
       [ 0.18367347,  0.81632653],
       [ 0.32653061,  0.3877551 ],
       [ 0.10204082,  0.97959184],
       [ 0.59183673,  0.87755102],
       [ 0.81632653,  0.87755102],
       [ 0.34693878,  0.44897959],
       [ 0.28571429,  0.51020408],
       [ 0.7755102 ,  0.97959184],
       [ 0.04081633,  0.75510204],
       [ 0.42857143,  0.79591837],
       [ 0.53061224,  0.79591837],
       [ 0.16326531,  0.46938776],
       [ 0.        ,  0.79591837],
       [ 0.04081633,  0.14285714],
       [ 0.18367347,  0.73469388]])

In [18]:
[1]*10

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [19]:
import tensorflow as tf

X = tf.random_uniform([256, 32]);
Y = tf.split(X,2,0)
Y_shape = tf.shape(Y[1])

sess = tf.Session()
X_v,Y_v,Y_shape_v = sess.run([X,Y,Y_shape]) 

In [20]:
print X.shape

(256, 32)


In [ ]:
print Y[1].shape

In [ ]:
?tf.concat

In [ ]:
a = [[1,2,3], [4,5,6]]

In [ ]:
a

In [ ]:
b = tf.convert_to_tensor(a)

In [ ]:
b_v = sess.run(b)

In [ ]:
b_v.shape

In [ ]:
u_all_occupants = np.array([[1,2,3,4, 13, 14],[5,8,7,6, 15, 16], [12,10,11,9, 17, 18]])

In [ ]:
u_all_occupants

In [ ]:
concerned_ind = np.array([[0,2,2,3],[0,2,3,1],[1,3,0,2]])

In [ ]:
u_all_occupants[np.arange(u_all_occupants.shape[0])[:,None],concerned_ind]

In [ ]:
u_all_occupants.shape

In [ ]:
np.arange(u_all_occupants.shape[0])[:,None]

In [ ]:
u_all_occupants[np.arange(u_all_occupants.shape[0])[:,None]]

In [ ]:
# now let's say we have observed following actions (2 actions for each occupant)
# for occ 1 : we see from ind 0 --> ind 2 and ind 2 to ind 3
# for occ 2 : we see from ind 0 --> ind 3 and ind 2 to ind 1
# for occ 3 : we see from ind 1 --> ind 0 and ind 3 to ind 2

In [ ]:
# concerned matrix indices should work as follows
# for occ 1 [0,2,2,3]
# for occ 2 [0,2,3,1]
# for occ 3 [1,3,0,2]
# concerned matrix is then given as follow;
# [1, 3, 3, 4]
# [5, 7, 6, 8]
# [10, 9, 12, 11]

In [ ]:
#A[np.arange(A.shape[0])[:,None],B]

In [ ]:
import numpy as np
values = np.array([
    [5,4,100],
    [10,20,500]
])
reorder_rows = np.array([
    [1,2,0],
    [0,2,1]
])

import tensorflow as tf

values = tf.constant(values)
reorder_rows = tf.constant(reorder_rows, dtype=tf.int32)
x = tf.tile(tf.range(tf.shape(values)[0])[:,tf.newaxis], [1,tf.shape(values)[1]])
res = tf.gather_nd(values, tf.stack([x, reorder_rows], axis=-1))
sess = tf.InteractiveSession()
res.eval()


In [ ]:
x

In [ ]:
x = tf.ones((10,10,10))
y = x[:, tf.newaxis] # or y = x [:, None]
print(y.shape)

In [3]:
import numpy as np
import tensorflow as tf
values = np.array([[1,2,3,4, 13, 14],[5,8,7,6, 15, 16], [12,10,11,9, 17, 18]])
values = tf.constant(values)

In [4]:
concerned_ind = np.array([[0,2,2,3],[0,2,3,1],[1,3,0,2]])
concerned_ind = tf.constant(concerned_ind)

In [ ]:
rows = tf.constant(np.arange(10*3).reshape(10,3), dtype=tf.float64)
selector = tf.constant([[0], [1], [0], [2], [1], [0], [0], [2], [2], [1]])

idx = tf.stack([tf.reshape(tf.range(rows.shape[0]), (-1,1)), selector], axis=-1)

res = tf.gather_nd(rows, idx)

In [ ]:
res.eval()

In [ ]:
rows.eval()

In [ ]:
idx.eval()

In [ ]:
selector.eval()

In [ ]:
def get_element(a, indices):
    """
    Outputs (ith element of indices) from (ith row of a)
    """
    return tf.map_fn(lambda x: tf.gather_nd(x[0], x[1]), 
                                  (a, indices),
                                  dtype = tf.float32)

In [ ]:
A = tf.constant(np.array([[1,2,3],
                          [4,5,6],
                          [7,8,9]], dtype = np.float32))

idx = tf.constant(np.array([[2],[1],[0]]))
elems = get_element(A, idx)

with tf.Session() as sess:
    e = sess.run(elems)

print(e)

In [ ]:
rows = tf.constant(np.arange(10*3).reshape(10,3), dtype=tf.float64)
selector1 = tf.constant([[0], [1], [0], [2], [1], [0], [0], [2], [2], [1]])
selector2 = tf.constant([[1], [1], [0], [2], [1], [0], [0], [2], [2], [1]])

idx1 = tf.stack([tf.reshape(tf.range(rows.shape[0]), (-1,1)), selector1], axis=-1)
idx2 = tf.stack([tf.reshape(tf.range(rows.shape[0]), (-1,1)), selector2], axis=-1)

res1 = tf.gather_nd(rows, idx1)
res2 = tf.gather_nd(rows, idx2)

In [ ]:
res1.eval()

In [ ]:
res2.eval()

In [6]:
import numpy as np
values = np.array([[1,2,3,4, 13, 14],[5,8,7,6, 15, 16], [12,10,11,9, 17, 18]])
values = tf.constant(values)
concerned_ind_numpy = np.array([[0,2,2,3],[0,2,3,1],[1,3,0,2]])
concerned_ind = tf.constant(concerned_ind_numpy)

In [7]:
for i in concerned_ind_numpy:
    print i

[0 2 2 3]
[0 2 3 1]
[1 3 0 2]


In [8]:
concerned_ind.shape

TensorShape([Dimension(3), Dimension(4)])

In [9]:
splits = tf.split(concerned_ind, num_or_size_splits=concerned_ind.shape[1],axis = 1)

In [10]:
splits[0].eval()

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

In [11]:
def gather_concerned_utilities(utility_matrix, concerned_ind_mat):
    """
    Gather concerned utility function values for each occupant
    """
    splits = tf.split(concerned_ind_mat, num_or_size_splits=concerned_ind_mat.shape[1],axis = 1)
    for i,s in enumerate(splits):
        print i
        idx = tf.stack([tf.reshape(tf.range(utility_matrix.shape[0]), (-1,1)), tf.to_int32(s)], axis=-1)
        res = tf.gather_nd(utility_matrix, idx)
        res_flatten = tf.reshape(res, [-1])
        res_list.append(res_flatten)
    concerned_mat = tf.stack(res_list) 
    return concerned_mat

In [12]:
concerned_mat = gather_concerned_utilities(values, concerned_ind)

0


NameError: global name 'res_list' is not defined

In [13]:
with tf.Session() as sess:
    e = sess.run(concerned_mat) 

NameError: name 'concerned_mat' is not defined

In [ ]:
e

In [ ]:
idx0 = tf.stack([tf.reshape(tf.range(values.shape[0]), (-1,1)), tf.to_int32(splits[0])], axis=-1)
res0 = tf.gather_nd(values, idx0)

In [ ]:
res0.eval()

In [ ]:
res_list = []
for s in splits:
    idx = tf.stack([tf.reshape(tf.range(values.shape[0]), (-1,1)), tf.to_int32(s)], axis=-1)
    res = tf.gather_nd(values, idx)
    res_flatten = tf.reshape(res, [-1])
    res_list.append(res_flatten)
    

In [ ]:
tf.stack(res_list).eval().shape

In [ ]:
res.eval().shape

In [ ]:
tf.reshape(res, [-1]).eval().shape

In [ ]:
H1 = tf.c